name: Submission Tracker
description: Submit a Topic Guide to DS Essentials.
title: "[SUBMISSION]: "
labels: 'enhancement'
body:
  - type: markdown
    attributes:
      value: |
        Use this template submit your Topic Guide and ensure the necessary metadata are available.  
  - type: textarea
    id: title
    attributes:
      label: Title
      description: What is the title of the Topic Guide?
      placeholder: Title of the Topic Guide.
      value: <insert title here>
    validations:
      required: true
  - type: textarea
    id: summary
    attributes:
      label: Summary
      description: Please summarize the Topic Guide's purpose in two sentences or less.
      placeholder: Summary of the Topic Guide.
      value: <insert summary here>
    validations:
      required: true
  - type: textarea
    id: contributors
    attributes:
      label: Contributors
      description: Please specify the full names and ORCID iDs of the contributors to the Topic Guide.
      placeholder: Contributors to the Topic Guide.
      value: <First Name, Last Name, ORCID iD>
    validations:
      required: true
  - type: input
    id: submission-date
    attributes:
      label: Submission Date
      description: Please specify the date on which the first draft was submitted.
      placeholder: Date of first draft submission.
      value: <YYYY-MM-DD>
    validations:
      required: true
  - type: textarea
    id: related-topics
    attributes:
      label: Related Topics
      description: Are there any existing Topic Guides that may relate to/be referenced to your Topic Guide?
      placeholder: List any existing topic guides that may relate to/be referenced in some way.
      value: <1. Topic 1>
    validations:
      required: true
  - type: input
    id: google-doc-url
    attributes:
      label: Link to Google Doc
      description: Please provide to link the the Google Doc of your submission.
      placeholder: Google Doc URL.
      value: <insert url here>
    validations:
      required: true
  - type: checkboxes
      id: access-requirements
      attributes:
        label: Access Requirements
        description: Please specify if you want to restrict access to your Google Doc until it's finalized.
        options:
          - label: Yes, I would like to restrict access to the Google Doc.
          - label: No, there is no need to restrict access to the Google Doc.
      validations:
        required: true
  - type: checkboxes
      id: submission-checklist
      attributes:
        label: Submission Checklist
        description: Please specify if you want to restrict access to your Google Doc until it's finalized.
        options:
          - label: Learning Objectives
          - label: Introduction to the Topic
          - label: Relevance to the Library Sector
          - label: Hands-On Activity & Other Self-Guided Tutorials
          - label: Recommended Reading & Viewing
          - label: Taking Next Steps
      validations:
        required: true
  - type: textarea
    id: comments
    attributes:
      label: comments
      description: Please use the following text area to include any other notes or comments. This can also include a (current) status statement and action points.
      placeholder: Notes and Comments.
      value: <status update / action points / comments / to-dos / notes>
    validations:
      required: true