project:
  type: book

execute: 
  freeze: auto

book:    
  chapters:
    - part: "**ABOUT**"
      chapters:
        - index.qmd
        - project-overview.qmd
        - part: contributing.qmd
          chapters:
            - guidelines.qmd
        - licensing.qmd
        - contact.qmd
    - topicguides.qmd
    - ml-ai.qmd
    - collectionsasdata.qmd
    - lod.qmd
    - iiif.qmd
    - api.qmd
    - dataviz.qmd
    - part: getting-started-with-programming.qmd
      chapters:
        - r.qmd
        - python.qmd
    - part: "**GENERAL RESOURCES**"
      chapters:
        - references.qmd
        - reports.qmd
        - training-platforms.qmd
        - networks.qmd
    
  sidebar:
    logo: images/NewLogo.png
    collapse-level: 1
  repo-url: https://github.com/libereurope/ds-essentials
  repo-actions: [edit]
  comments: 
    utterances:
      repo: libereurope/ds-essentials

bibliography: references.bib

format:
  html:
    theme: cosmo

website:
  google-analytics: "G-54HL7T1Z2K"
  cookie-consent: true
