project:
  type: book

execute: 
  freeze: auto

book:  
  title: "DS Essentials"
  google-analytics: 
    tracking-id: "G-54HL7T1Z2K"
  reader-mode: true
  search: true
  page-footer: 
    border: false
    background: dark
    left: | 
      A 2023-2027 <a href="https://libereurope.eu/working-groups">LIBER Working Group</a> collaboration between <a href="https://libereurope.eu/working-group/digital-scholarship-and-digital-cultural-heritage-collections-working-group/">Digital Scholarship and Digital Cultural Heritage </a> and <a href="https://libereurope.eu/working-group/liber-data-science-in-libraries-working-group/">Data Science in Libraries</a> 
    

  
  chapters:
    - part: "**ABOUT**"
      chapters:
        - index.qmd
        - project-overview.qmd
        - contributing.qmd
        - guidelines.qmd
        - licensing.qmd
        - contact.qmd
    - topicguides.qmd
    - ml-ai.qmd
    - collectionsasdata.qmd
    - lod.qmd
    - iiif.qmd
    - dataviz.qmd
    - github.qmd
    - workingwdata.qmd
    - api.qmd
    - part: "**GENERAL RESOURCES**"
      chapters:
        - references.qmd
        - reports.qmd
        - training-platforms.qmd
        - networks.qmd
        - dstp.qmd
    
  sidebar:
    logo: images/NewLogo.png
    style: "docked"
    collapse-level: 1
  repo-url: https://github.com/libereurope/ds-essentials
  repo-actions: [edit, issue]
  comments: 
    utterances:
      repo: libereurope/ds-essentials

bibliography: references.bib

format:
  html:
    theme: cosmo


