project:
  type: book

execute: 
  freeze: auto

book:
  title: "Digital Scholarship & Data Science Essentials for Library Professionals"
  author: Data Science in Libraries WG<br>Digital Scholarship & Digital Cultural Heritage WG
  date: last-modified
  chapters:
    - index.qmd
    - topicguides.qmd
    - part: getting-started-with-programming.qmd
      chapters:
        - r.qmd
        - python.qmd
    - part: ml-ai.qmd
      chapters:
        - llms.qmd
    - iiif.qmd
    - part: "**GENERAL RESOURCES**"
      chapters:
        - references.qmd
        - reports.qmd
        - training-platforms.qmd
        - networks.qmd
    - part: "**ABOUT**"
      chapters:
        - project-overview.qmd
        - contributing.qmd
        - guidelines.qmd
        - licensing.qmd
        - contact.qmd
    
  sidebar:
    logo: images/liber-logo.jpg
    collapse-level: 1
  repo-url: https://github.com/libereurope/ds-essentials
  repo-actions: [edit]
  comments: 
    utterances:
      repo: libereurope/ds-essentials

bibliography: references.bib

format:
  html:
    theme: cosmo


